INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("AM6301","Continuum Mechanics",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("BS6203","Applied Stress Analysis",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CNS5200","Advanced Bio-Molecular Architecture",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS3150","Molecular Architecture",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS3725","Introduction to NLP",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4450","Web data and Knowledge Management",5,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4464","Service Oriented Architectures with Lisp",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4650","Software Quality Management in Practice",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4731","Information Retrieval and Extraction",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4745","Designing Speech Systems",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4772","Artificial Neural Networks",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4785","Introduction to Cognitive Science",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS4852","Performance Evaluation Concepts",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS5405","Data Warehousing and Data Mining",5,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS5460","Enterprise Information Systems Structures",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS5728","NLP Applications",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9913","Evolution of Telugu Novel",2,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9914","Gandhi and India",2,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9918","Thermodynamics and Statistical Mechanics",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9919","Readings from Modern Hindi Literature",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9920","Spoken Language Interfaces",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9922","CMOS Radio-Frequency Integrated Circuit Design",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9923","Natural Resources Management",2,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9925","Computational Structural Biology",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9930","Introduction to Computer Aided Drug Design",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9935","Introduction to Cognitive Neurophysiology",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9936","Introduction to Medical Informatics",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9937","Understanding Work and Life",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CS9997","BioStatistics",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("CSE548","Multi Agent Systems",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("EC5303","Data Compression",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("ECE361","Introduction to VLSI",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("ECE441","Adaptive Signal Processing",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("EE3000","Networks and Transmission Lines",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("EE3001","Electromagnetic Theory",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("EE3300","Error Correction Codes I",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("EE4500","Electrical Power Distribution Systems",2,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("ET3300","Introduction to Telecommunication",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS105","English-II",2,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS107","Human Values-II",2,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS2000","Introduction to Philosophy",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS2095","Musicology:Study Understanding and Appreciation",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS2780","Science and Society",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS3005","The Making of the Modern Mind",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS3051","Religion Society and Cultural Heritage of India",2,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS3201","Introduction to Accountancy and Finance",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS3720","Globalization and Social Development",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS3850","Introduction to Ethics",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS5092","Language Topology and Universals",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS5093","Linguistics-II: Language & Society",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HS5096","Linguistic Data",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HSD201","Theoretical Humanities",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HSS323","Introduction to Vedic Dharshan",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HSS363","Dharma Polity and Constitution of India",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("HSS411","Philosophy of Mind",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("MA4578","Multivariate Analysis",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("MG2100","Introduction to Economics",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("MG4551","Decision Support Systems",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("MG4900","ICT for Development",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SCI320","Introduction to Biology",3,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SCI344","Organic Chemistry and BMSID",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SCI551","Introduction to Bioinformatics",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SCI622","Advanced Biology",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SCI651","Advanced Bioinformatics",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SCI761","Topics in Nanosciences",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SE6301","Structural Dynamics",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SE6401","Earthquake Engineering",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SE6503","Advanced Structural Design",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("SE7702","Theory of Elasticity",4,"elective",NULL);
INSERT INTO course3(courseId,courseName,credit,cType,prerequisite) VALUES("TMP18","Life Literature and Thought",2,"elective",NULL);
