INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS1001","Physics II",2,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS1010","IT Workshop-I",2,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS1011","IT Workshop-II",3,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS104","Computer System Organization",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS1200","Digital Logic Design",2,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS2010","IT Workshop-III",3,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS2200","Computer Organization",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS3155","Compilers",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS3300","Operating Systems-UG",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS3311","Computer Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS3350","Computer Networks",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS3400","Database Management Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS3500","Computer Graphics",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4210","Parallel Programming",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4401","Distributed Database Management Systems",5,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4462","Internals of Application Servers",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4725","Natural Language Processing",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4740","Speech Technology",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4750","Digital Image Processing",5,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4770","Pattern Recognition",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS4780","Mobile Robotics",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS5765","Computer Vision",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS5770","Machine Learning",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS5905","Spatial Informatics",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS9917","Quantum Theory",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS9924","Game Theory",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS9932","Radar Signal Processing",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS9934","Complex Systems-I",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS9994","Speech Signal Processing",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CS9998","Program Dynamics",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CSE431","Distributed Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CSE441","Database Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("CSE541","Advances in Database Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("EC103","Basic Electronic Circuits",5,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("EC239","Digital Signal Analysis and Applications",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("EC3050","Analog and Digital Circuits",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("EC3106","Multimedia Signal Processing",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("EC3200","Microprocessor based System Design",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("EC3300","Analog and Digital Communications",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ECE291","Electronic Workshop",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ECE325","Embedded Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ECE341","Digital Signal Processing",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("EG201","Engineering Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ET3105","Signals & Systems",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ET4291","Embedded Systems-II",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ET4350","Analog and Mixed Signal IC Design",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ET4561","VLSI Algorithms",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ET4600","VLSI-II",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ET4601","VLSI-III",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("ET5650","Architectural Design with ICs",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("HS5091","Computational Linguistics-II",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("SC1000","Physics I",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("SC4250","Structural Bioinformatics",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("SCI432","Quantum Mechanics-II",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("SCI433","Modeling and Simulation",5,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("SCI550","Statistics and Mathematics",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("SE6203","Numerical Modeling of Structures and fluids",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("TEMP31","Mechanics of Materials",4,"system",NULL);
INSERT INTO course1(courseId,courseName,credit,cType,prerequisite) VALUES("TEMP41","Concrete Engineering",4,"system",NULL);
