INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("AM6201","Finite Element Method",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CE335","Communication Theory-I",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS1000","Computer Programming",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS103","Data Structures",5,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS2100","Data Structures & Algorithms",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS3000","Advanced Problem Solving",6,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS3001","Scripting And Computer Environments",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS3010","Computing Tools",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS3101","Theory of Computation",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS3110","Algorithms",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS3111","Computer Problem Solving",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS3301","Operating Systems-PG",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS4110","Cryptography and Network Security",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS4175","Computational Geometry",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS4200","Modern Computer Architecture",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS4201","Computer Architecture",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS4405","Applied Data Mining",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS4746","Speech Systems",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS4771","Soft Computing",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS5470","System and Network Security",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS6476","Topics in Information Security",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS6600","Topics in Software Architecture",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS9916","Topics in Ontology",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS9921","Computational Methods",5,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CS9929","Usability Engineering",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSC251","Graphics",2,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSC311","Formal Methods",2,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSC371","Artificial Intelligence",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSC461","Software Engineering",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSE411","Complexity and Advanced Algorithms",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSE415","Principles of Programming Languages",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSE418","Principles of Information Security",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSE471","Statistical Methods in AI",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("CSE481","Optimization Methods",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("EC3600","VLSI Design",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("EC3800","Communication Networks",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("EC4300","Information Theory and Coding",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("EE3100","Linear Control Systems",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("ET1000","Electrical Science I",2,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("ET1002","Electrical Science II",2,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("ET1111","Formal Verification",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("ET2050","Electronic Circuits",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("ET6651","Design for Testability",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("GE6301","Foundation Engineering and Design",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("HS5090","Computational Linguistics-I",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("HS5094","A Course on Generalized Syntax",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("MA1000","Mathematics-I",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("MA1010","Mathematics-II",5,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("MA3100","Linear Algebra",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("MA3200","Mathematics-III",5,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("MA3201","Discrete Maths and Algorithms",6,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("MA3500","Probability and Random Processes",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("MA5910","Graph Theory of Computer Scientists",2,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("SCI1","Bioinformatics Resources",2,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("SCI202","Science-II",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("SCI341","General and Structural Chemistry",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("SCI372","Science Lab-II",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("SCI434","Statistical Mechanics",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("SCI541","Biomolecular Structure Interaction and Dynamics",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("TEMP11","Information Security: Research and Management",4,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("TEMP16","Generative Ontology",3,"foundation",NULL);
INSERT INTO course2(courseId,courseName,credit,cType,prerequisite) VALUES("TEMP21","Information Security Audit and Assurance",4,"foundation",NULL);
