INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC100","abhijit.mitra@faculty.iiit.ac.in","Mumbai",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC101","amitash.ojha@faculty.iiit.ac.in","Hyderabad",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC102","ananda.swarup.das@faculty.iiit.ac.in","Hyderabad",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC103","a.giridhar.rao@faculty.iiit.ac.in","Varanasi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC104","anoop.namboodiri@faculty.iiit.ac.in","New Delhi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC105","anubha.gupta@faculty.iiit.ac.in","Chennai",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC106","a.rameshwar@faculty.iiit.ac.in","Lucknow",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC107","ashok.kumar.das@faculty.iiit.ac.in","Chennai",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC108","avasarala.srinivas@faculty.iiit.ac.in","Chennai",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC109","azeemuddin.syed@faculty.iiit.ac.in","Mumbai",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC110","banatanwi.das.mahapatra@faculty.iiit.ac.in","Mumbai",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC111","bezawada.bruhadeshwar@faculty.iiit.ac.in","New Delhi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC112","b.gopalakrishnan@faculty.iiit.ac.in","New Delhi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC113","bhaskar.reddy@faculty.iiit.ac.in","New Delhi",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC114","bipin.indurkhya@faculty.iiit.ac.in","New Delhi",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC115","b.prabhakar@faculty.iiit.ac.in","Bangalore",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC116","b.yegnanarayana@faculty.iiit.ac.in","Bangalore",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC117","chakrapani.bommaraju@faculty.iiit.ac.in","Varanasi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC118","chanchal.mitra@faculty.iiit.ac.in","New Delhi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC119","chandrasekher.mukku@faculty.iiit.ac.in","Hyderabad",1100000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC120","chenna.rajaram@faculty.iiit.ac.in","New Delhi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC121","c.n.kaul@faculty.iiit.ac.in","New Delhi",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC122","c.v.jawahar@faculty.iiit.ac.in","Bangalore",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC123","deb.kamal.ganguly@faculty.iiit.ac.in","Chennai",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC124","deva.priyakumar@faculty.iiit.ac.in","New Delhi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC125","dipti.misra.sharma@faculty.iiit.ac.in","Lucknow",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC126","e.vijay.prakash@faculty.iiit.ac.in","Lucknow",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC127","garimella.ramamurthy@faculty.iiit.ac.in","Lucknow",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC128","g.syamasundar.reddy@faculty.iiit.ac.in","Lucknow",800000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC129","harjinder.singh@faculty.iiit.ac.in","Varanasi",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC130","jayanthi.sivaswamy@faculty.iiit.ac.in","Varanasi",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC131","jayashree.ratnam@faculty.iiit.ac.in","New Delhi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC132","kamalakar.karlapalem@faculty.iiit.ac.in","Chennai",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC133","kannan.srinathan@faculty.iiit.ac.in","Bangalore",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC134","kirti.garg@faculty.iiit.ac.in","Varanasi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC135","kishore.kothapalli@faculty.iiit.ac.in","Lucknow",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC136","kishore.s.prahallad@faculty.iiit.ac.in","Mumbai",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC137","k.madhava.krishna@faculty.iiit.ac.in","Bangalore",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC138","k.r.sarma@faculty.iiit.ac.in","Hyderabad",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC139","k.s.rajan@faculty.iiit.ac.in","Chennai",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC140","k.viswanath@faculty.iiit.ac.in","New Delhi",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC141","lakshmi.bai@faculty.iiit.ac.in","Chennai",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC142","marimuthu.krishnan@faculty.iiit.ac.in","New Delhi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC143","m.venkateshwarlu@faculty.iiit.ac.in","Hyderabad",1000000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC144","mulualem.teku@faculty.iiit.ac.in","Hyderabad",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC145","nand.kishore.acharya@faculty.iiit.ac.in","Bangalore",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC146","naveena.yanamala@faculty.iiit.ac.in","Mumbai",1000000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC147","navjyoti.singh@faculty.iiit.ac.in","Mumbai",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC148","neelima.satyam.d@faculty.iiit.ac.in","Varanasi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC149","nita.parekh@faculty.iiit.ac.in","Chennai",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC150","peri.bhaskararao@faculty.iiit.ac.in","Hyderabad",1000000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC151","piyush.bansal@faculty.iiit.ac.in","New Delhi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC152","p.j.narayanan@faculty.iiit.ac.in","Mumbai",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC153","p.krishna.reddy@faculty.iiit.ac.in","Bangalore",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC154","pooja.kaul@faculty.iiit.ac.in","Varanasi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC155","pradeep.kumar.ramancharla@faculty.iiit.ac.in","Lucknow",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC156","p.ramachandra.prasad@faculty.iiit.ac.in","Varanasi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC157","pranav.k.vasishta@faculty.iiit.ac.in","New Delhi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC158","prasad.pingali@faculty.iiit.ac.in","Chennai",650000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC159","prashanth.reddy.mannem@faculty.iiit.ac.in","Bangalore",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC160","p.r.k.rao@faculty.iiit.ac.in","Mumbai",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC161","p.venkata.dilip.kumar@faculty.iiit.ac.in","Varanasi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC162","radhika.mamidi@faculty.iiit.ac.in","Varanasi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC163","rajeev.sangal@faculty.iiit.ac.in","Hyderabad",1600000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC164","rambabu.kalla@faculty.iiit.ac.in","Chennai",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC165","ramesh.loganathan@faculty.iiit.ac.in","Bangalore",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC166","r.govindarajulu@faculty.iiit.ac.in","Bangalore",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC167","r.k.bagga@faculty.iiit.ac.in","Lucknow",850000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC168","satyam.mandavalli@faculty.iiit.ac.in","Hyderabad",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC169","saurabh.barjatiya@faculty.iiit.ac.in","Lucknow",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC170","shatrunjay.rawat@faculty.iiit.ac.in","Lucknow",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC171","shubhajit.roy.chowdhury@faculty.iiit.ac.in","Bangalore",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC172","soma.paul@faculty.iiit.ac.in","New Delhi",800000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC173","sonal.nimbkar@faculty.iiit.ac.in","Bangalore",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC174","sriram.v@faculty.iiit.ac.in","Lucknow",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC175","suresh.purini@faculty.iiit.ac.in","Bangalore",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC176","suryakanth.v.g@faculty.iiit.ac.in","Varanasi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC177","s.v.ramanan@faculty.iiit.ac.in","Lucknow",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC178","tapan.kumar.sau@faculty.iiit.ac.in","New Delhi",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC179","u.deva.priyakumar@faculty.iiit.ac.in","Hyderabad",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC180","vasudeva.varma@faculty.iiit.ac.in","Bangalore",1200000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC181","venkatesh.choppella@faculty.iiit.ac.in","Chennai",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC182","vijaya.sankara.rao.p@faculty.iiit.ac.in","Mumbai",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC183","vikram.pudi@faculty.iiit.ac.in","New Delhi",700000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC184","vinay.kumar.mittal@faculty.iiit.ac.in","Varanasi",500000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC185","vishal.garg@faculty.iiit.ac.in","Varanasi",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC186","y.raghu.reddy@faculty.iiit.ac.in","Chennai",900000);
INSERT INTO faculty2(facultyId,emailId,hometown,salary) VALUES("FAC187","vinal.mittal@faculty.iiit.ac.in","Bangalore",500000);
