INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC100","BIO","Abhijit Mitra","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC101","CNS","Amitash Ojha","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC102","CSE","Ananda Swarup Das","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC103","CL","A Giridhar Rao","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC104","CSE","Anoop Namboodiri","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC105","PWR","Anubha Gupta","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC106","CNS","A Rameshwar","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC107","CSIS","Ashok Kumar Das","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC108","CSIS","Avasarala Srinivas","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC109","CL","Azeemuddin Syed","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC110","PWR","Banatanwi Das Mahapatra","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC111","CSE","Bezawada Bruhadeshwar","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC112","CASE","B Gopalakrishnan","Visiting Faculty");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC113","BIO","Bhaskar Reddy","Research Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC114","BIO","Bipin Indurkhya","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC115","CNS","B Prabhakar","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC116","CSE","B Yegnanarayana","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC117","PWR","Chakrapani Bommaraju","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC118","CSIS","Chanchal Mitra","Visiting Faculty");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC119","ECE","Chandrasekher Mukku","Research Scientist");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC120","CL","Chenna Rajaram","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC121","ECE","C N Kaul","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC122","CSE","C V Jawahar","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC123","CSIS","Deb Kamal Ganguly","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC124","CSIS","Deva Priyakumar","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC125","CNS","Dipti Misra Sharma","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC126","CSE","E Vijay Prakash","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC127","VLSI","Garimella Ramamurthy","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC128","CSIS","G Syamasundar Reddy","Research Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC129","EHD","Harjinder Singh","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC130","ECE","Jayanthi Sivaswamy","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC131","CNS","Jayashree Ratnam","Visiting Faculty");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC132","CSE","Kamalakar Karlapalem","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC133","CSIS","Kannan Srinathan","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC134","CL","Kirti Garg","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC135","CNS","Kishore Kothapalli","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC136","CL","Kishore S Prahallad","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC137","VLSI","K Madhava Krishna","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC138","EHD","K R Sarma","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC139","VLSI","K S Rajan","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC140","EHD","K Viswanath","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC141","VLSI","Lakshmi Bai","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC142","CSIS","Marimuthu Krishnan","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC143","VLSI","M Venkateshwarlu","Professor of Eminence");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC144","BIO","Mulualem Teku","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC145","CNS","Nand Kishore Acharya","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC146","CNS","Naveena Yanamala","Post Doctoral Associate");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC147","ECE","Navjyoti Singh","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC148","CSE","Neelima Satyam D","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC149","ECE","Nita Parekh","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC150","CNS","Peri Bhaskararao","Institute Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC151","VLSI","Piyush Bansal","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC152","VLSI","P J Narayanan","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC153","VLSI","P Krishna Reddy","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC154","CASE","Pooja Kaul","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC155","CNS","Pradeep Kumar Ramancharla","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC156","VLSI","P Ramachandra Prasad","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC157","VLSI","Pranav K Vasishta","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC158","CSE","Prasad Pingali","Faculty");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC159","CNS","Prashanth Reddy Mannem","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC160","CASE","P R K Rao","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC161","CSE","P Venkata Dilip Kumar","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC162","CSE","Radhika Mamidi","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC163","CL","Rajeev Sangal","Director");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC164","CNS","Rambabu Kalla","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC165","PWR","Ramesh Loganathan","Visiting Faculty");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC166","CSE","R Govindarajulu","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC167","EHD","R K Bagga","Advisor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC168","BIO","Satyam Mandavalli","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC169","CSE","Saurabh Barjatiya","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC170","CSE","Shatrunjay Rawat","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC171","ECE","Shubhajit Roy Chowdhury","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC172","CL","Soma Paul","Research Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC173","CASE","Sonal Nimbkar","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC174","BIO","Sriram V","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC175","BIO","Suresh Purini","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC176","EHD","Suryakanth V G","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC177","VLSI","S V Ramanan","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC178","VLSI","Tapan Kumar Sau","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC179","VLSI","U Deva Priyakumar","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC180","CSE","Vasudeva Varma","Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC181","CSE","Venkatesh Choppella","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC182","PWR","Vijaya Sankara Rao P","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC183","CSE","Vikram Pudi","Assistant Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC184","BIO","Vinay Kumar Mittal","Lecturer");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC185","CNS","Vishal Garg","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC186","PWR","Y Raghu Reddy","Associate Professor");
INSERT INTO faculty1(facultyId,deptId,facultyName,facultyTitle) VALUES("FAC187","ECE","Vinal Mittal","Lecturer");
